### ISSUE TITLE
Group Targeting

### ISSUE THREAD

**Issue by ghost** [NodeBB/nodebb-widget-essentials#11]
The widgets plugin has the option to hide widgets from anonymous users. It would be great to have the functionality to hide widgets from users, or select the usergroups that can see a specific widget.This would be perfect for targeting widgets towards a specific usergroup, or showing messages to guests only.

**Comment by barisusakli** [comment]
This was added a while ago
![image](https://user-images.githubusercontent.com/2583394/54936423-d42bb180-4ef8-11e9-91e1-ebc262bfea8c.png)
