### ISSUE TITLE
Stats widget large numbers overlap when it's on the sidebar

### ISSUE THREAD

**Issue by akhoury** [NodeBB/nodebb-widget-essentials#20]
![screen shot 2015-05-13 at 12 51 23 pm](https://cloud.githubusercontent.com/assets/1398375/7615945/f122945e-f96e-11e4-9562-b38c70e49c22.png)

I think it's safe to assume that there will not be more than 6 chars; 

999.9M
after that we should see
1.0B ... 999.9B
etc.

**Comment by barisusakli** [comment]
Just took 4 years npnp
![image](https://user-images.githubusercontent.com/2583394/54939258-7c904480-4efe-11e9-9830-ee4324e500af.png)
