### ISSUE TITLE
Broken links on "read more"...

### ISSUE THREAD

**Issue by jenkin** [NodeBB/nodebb-widget-essentials#21]
Recent posts in widgets have the read more link pointing to this url (see "relative_path" string): http://[domain]/category/[cid]/**%7Brelative_path%7D**/topic/[tid]0/[title]/[pid]

A broken template? I'm using v0.8.2...

**Comment by jenkin** [comment]
In `public/templates/partials/posts.tpl`, row 12, it seems the `{relative_path}` is not substituted and remains in the final url.

**Comment by jenkin** [comment]
Ehi, if I change `{relative_path}` to `{relativePath}` it works, also on user image link... maybe relativePath is simply not defined, so the template use an empty string? Can the problem be the underscore in the template?

**Comment by ASCIIcat** [comment]
I have found removing `{relative_path}/` entirely seems to work fine on my setup for both the user image as well as the read more link.
