### ISSUE TITLE
Widget order

### ISSUE THREAD

**Issue by joetm** [NodeBB/nodebb-widget-essentials#28]
Under 'global', I have specified a footer.
Under 'categories.tpl', I added the "Active Users" widget.

Problem: the active users show up below the site's footer.

There should be a way to specify the order of the widgets across the categories, e.g. with numbers (the higher the number, the lower the widget is displayed).
Or the global widget should always be added last.

**Comment by barisusakli** [comment]
![image](https://user-images.githubusercontent.com/2583394/54938964-cfb5c780-4efd-11e9-9205-9c1e5e99d134.png)
https://github.com/NodeBB/NodeBB/issues/6199
