### ISSUE TITLE
No user displayed when teaser post is not available

### ISSUE THREAD

**Issue by RoiEXLab** [NodeBB/nodebb-widget-essentials#35]
A regression introduced in #33
When the admin of a forums sets the setting of Settings > Posts > Teaser to 'last-reply', topics with just one post (e.g. no replies) have a blank image.
Workaround is to set it to another setting.

**Comment by barisusakli** [comment]
This should be fixed in https://github.com/NodeBB/nodebb-widget-essentials/commit/b0a96004a96e7d1aa2aa050e8caad2f3afb02d8d

**Comment by RoiEXLab** [comment]
Great!
I will reopen in case I notice any issues once 1.6.2 is released
