### ISSUE TITLE
Suggested topics should be filtered by category of the parent topic

### ISSUE THREAD

**Issue by zipang** [NodeBB/nodebb-widget-essentials#37]
There is an option in the widget admin panel but it doesn't work on a topic : 
![suggested topics widget panel](https://i.imgur.com/oG1GrD6.png)
and yes, it's really requested that we could suggest other topics belonging to _the same category_ (forum) than a given topic.

**Comment by barisusakli** [comment]
That option wasn't doing anything and it has been removed a while ago, when this widget is placed on a topic page it will pull random topics from 
1. same tags
2. similar title
3. same category
