### ISSUE TITLE
Failed to lookup view "admin/html" in views directory "/home/user/nodebb/build/public/templates"

### ISSUE THREAD

**Issue by Rimann91** [NodeBB/nodebb-widget-essentials#39]
This worked fine on my local machine but after migrating to a remote server I receive this error when I try to  access widgets under the extend menu in admin toolbar.

`Failed to lookup view "admin/html" in views directory "/home/riley/nodebb/build/public/templates"`

**Comment by barisusakli** [comment]
This usually means you need to run `./nodebb build`
