### ISSUE TITLE
HTML widget: Category ID filter ignored

### ISSUE THREAD

**Issue by juan-g** [NodeBB/nodebb-widget-essentials#40]
The HTML widget has a potentially very useful **Category** filter that says: "Set the category ID you want to display this widget on".

However, after writing a category number and saving for the topic sidebar of **topic.tpl**, the widget appears on the topics of all categories. This looks like a bug.

**Comment by juan-g** [comment]
The Category ID filter works well on **category.tpl**, but not on **topic.tpl**.

**Comment by juan-g** [comment]
Maybe it's here:
```
function isVisibleInCategory(widget) {
	var cids = getCidsArray(widget);
	return !(cids.length && widget.templateData.template.category && cids.indexOf(parseInt(widget.templateData.cid, 10)) === -1);
}
```
([nodebb-widget-essentials/library.js](https://github.com/NodeBB/nodebb-widget-essentials/blob/master/library.js))

**Comment by juan-g** [comment]
Replacing:
```
&& widget.templateData.template.category &&
```
with:
```
&& (widget.templateData.template.category || widget.templateData.template.topic) &&
```
seems to work well.

**Comment by juan-g** [comment]
That's a very useful feature. Thank you! :+1:

**Comment by juan-g** [comment]
It's working great. Only a detail: Instead of

> Set the category ID you want to display this widget on

it should say

> Set the category IDs you want to display this widget on (separated by commas)

since it has this multiple ID functionality. Thanks!

**Comment by barisusakli** [comment]
https://github.com/NodeBB/nodebb-widget-essentials/commit/c8ea9b6647ddc54321b01e19a3cacc4436085733

**Comment by juan-g** [comment]
:+1:
