### ISSUE TITLE
Recent Cards carousel mode on pages besides "categories"

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/nodebb-widget-essentials#51]
In Recent Cards widget, it would be great if carousel mode can be turned on on topics or sub-category pages. Right now, it is only active on the main "categories" page. Thanks.

**Comment by AliCihan** [comment]
I would like to remind this improvement. It would be great to have "Carousel Mode" under sub-category pages..

**Comment by barisusakli** [comment]
https://github.com/NodeBB-Community/nodebb-plugin-recent-cards/commit/6aaf1c1e9026e0aa463d238ae5fae92d8cd5d2ee
