### ISSUE TITLE
Just have two widgets ？

### ISSUE THREAD

**Issue by wenlanhuitai** [NodeBB/nodebb-widget-essentials#55]
nodebb Install nodebb-widget-essentials ，then enable plugin，bug my widget just have global and grouds/detail.tpl

![EFEFA7EB-E773-42A2-9FEA-FAEEA5CBE4F8.png](https://i.loli.net/2021/06/27/2NmHanWub1A4DfQ.png)

**Comment by barisusakli** [comment]
This is controlled by the theme, switch to persona and rebuilt/restart it should show alot more areas.  
![image](https://user-images.githubusercontent.com/2583394/151641080-da1020cc-2a9d-48cb-8522-cc5271736952.png)
