### ISSUE TITLE
No matching version found for 5.0.4

### ISSUE THREAD

**Issue by wenlanhuitai** [NodeBB/nodebb-widget-essentials#56]
npm i nodebb-widget-essentials@5.0.4
npm ERR! code ETARGET
npm ERR! notarget No matching version found for nodebb-widget-essentials@5.0.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/coolning/.npm/_logs/2021-10-22T02_47_04_155Z-debug.log

**Comment by barisusakli** [comment]
try 5.0.5
