### ISSUE TITLE
the "recent view" widget does not work on /categories or /users page

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/nodebb-widget-essentials#57]
I added the "recent view" widget to the global sidebar. 

The first problem, the "new topic" and "all categories" buttons do not align anymore. 

The second problem, all categories dropdown does not work on pages like /categories or /users, whereas it works on /recent page. 

<img width="731" alt="Screen Shot 2022-01-19 at 11 11 34 PM" src="https://user-images.githubusercontent.com/52054408/150272060-5dfe07ee-fbd6-43a1-a1be-81ead6ed8db5.png">

**Comment by barisusakli** [comment]
I think that widget isn't meant to be used like a regular sidebar widget, if you want to show recent topics try the `Recent Topics` widget. I think the recent view tries to render the actual /recent page as a widget but it might not work if there are already conflicting data on the page. Maybe it was added to be used with the custom pages plugin to render the recent view on a custom url.

**Comment by AliCihan** [comment]
ok, got it. thanks 👍
