### ISSUE TITLE
topic specific widgets

### ISSUE THREAD

**Issue by AliCihan** [NodeBB/nodebb-widget-essentials#59]
If it will not affect the performance of the forum, it would be a nice addition just like category id specific HTML widgets... 

this issue can be closed if this change will affect the performance dramatically.

**Comment by barisusakli** [comment]
This should be easily doable for the html widget, I will take a look 🔜

**Comment by barisusakli** [comment]
5.0.8 should allow this

**Comment by barisusakli** [comment]
@AliCihan  use 5.0.9 had an issue in 5.0.8
