### ISSUE TITLE
How to get back the small Online users widget?

### ISSUE THREAD

**Issue by ledlamp** [NodeBB/nodebb-widget-essentials#65]
Originally the online users widget had only little user icons, but after some update they are now big rectangles with the user name and last active time. I want the array of little tiny icons back

**Comment by barisusakli** [comment]
You can use the old template https://raw.githubusercontent.com/NodeBB/nodebb-widget-essentials/c331e515b6d9530121753296ee28f93d9abf9364/public/templates/widgets/onlineusers.tpl

**Comment by ledlamp** [comment]
thx!!! i guess i have to install fork of the plugin
